apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-healthcheck-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: medik8s-system
  sources:
    # 1. Self Node Remediation Operator (Исполнитель ремедиации)
    - repoURL: 'https://github.com/medik8s/self-node-remediation.git'
      path: config/deploy
      targetRevision: v0.9.0 # Актуальный релиз или HEAD

    # 2. Node Healthcheck Operator (Детектор упавших нод)
    - repoURL: 'https://github.com/medik8s/node-healthcheck-operator.git'
      path: config/deploy
      targetRevision: v0.12.0 # Актуальный релиз

    # 3. Твои правила и конфиги (NodeHealthCheck + SelfNodeRemediationTemplate)
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      path: k8s/systems/node-healthcheck-operator
      targetRevision: HEAD
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true