apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  sources:
    - repoURL: 'https://helm.cilium.io/'
      chart: cilium
      targetRevision: 1.20.0
      helm:
        values: |
          # Жёстко задаем 1 реплику для работы на 1 ноде:
          operator:
            replicas: 1
          
          # Использование eBPF заменяет kube-proxy (стандартная практика для Talos)
          kubeProxyReplacement: true
          
          # Настройки взаимодействия с Kubernetes API на Talos
          k8sServiceHost: localhost
          k8sServicePort: 7445
          
          # Обязательные привилегии для работы BPF и контейнеров на Talos
          securityContext:
            privileged: true
          
          # Настройка cgroupv2 под особенности Talos OS
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup
          
          # Отключаем автоматический сброс состояния при перезапуске
          cleanState: false
          cleanBpfState: false
          
          # Включение и конфигурация Hubble
          hubble:
            enabled: true
            relay:
              enabled: true   # Агрегатор логов Hubble
              replicas: 1     # <--- Тоже 1 реплика
            ui:
              enabled: true   # Веб-интерфейс Hubble
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      path: k8s/systems/cilium

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true