apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  source:
    repoURL: 'oci://docker.io/envoyproxy/gateway-helm'
    chart: gateway-helm
    targetRevision: v1.8.3  # Актуальная версия!
    helm:
      parameters:
        - name: config.skipCreateGatewayClass
          value: "false"
        - name: config.skipCreateGateway
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Force=true