apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  sources:
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      path: k8s/systems/envoy-gateway
      targetRevision: HEAD
      directory:
        recurse: true
    - repoURL: 'oci://docker.io/envoyproxy/gateway-helm'
      chart: gateway-helm
      targetRevision: v1.8.3  # Актуальная версия!
      helm:
        parameters:
          - name: config.skipCreateGatewayClass
            value: "false"
          - name: config.skipCreateGateway
            value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Force=true