apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  sources:
    - repoURL: 'oci://docker.io/envoyproxy'
      chart: gateway-helm
      targetRevision: v1.1.0
      helm:
        valueFiles:
          - '$values/helm/systems/envoy-gateway/values.yaml'
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true