# apps/local-path-storage.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
  source:
    repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
    targetRevision: HEAD
    path: k8s/systems/local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true