apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
  sources:
    - repoURL: 'https://github.com/rancher/local-path-provisioner.git'
      path: deploy/chart/local-path-provisioner
      targetRevision: master
      helm:
        valueFiles:
          - '$values/helm/systems/local-path-provisioner/values.yaml'
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true