apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openebs
  sources:
    # 1. Готовый официальный оператор LocalPV прямо из GitHub
    - repoURL: 'https://raw.githubusercontent.com/openebs/localpv-provisioner/master/deploy/gitops/openebs-localpv-operator.yaml'
      targetRevision: HEAD
      directory:
        recurse: true

    # 2. Наш StorageClass из твоего Git-репозитория
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      path: k8s/systems/openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true