apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openebs
  sources:
    # 1. Скачиваем официальный Helm-чарт OpenEBS
    - repoURL: 'https://openebs.github.io/openebs'
      chart: openebs
      targetRevision: 4.1.1 # Или актуальная версия
      helm:
        valueFiles:
          - '$values/helm/systems/openebs/values.yaml'

    # 2. Подтягиваем наш values.yaml
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      ref: values

#    # 3. Накатываем манифест StorageClass openebs-hostpath из k8s/
#    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
#      targetRevision: HEAD
#      path: k8s/systems/openebs
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
#      - ServerSideApply=true