apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openebs
  sources:
    # 1. Официальный Helm-чарт OpenEBS v4 (из официального репо)
    - repoURL: 'https://openebs.github.io/openebs'
      chart: openebs
      targetRevision: 4.2.0
      helm:
        valueFiles:
          - '$values/helm/systems/openebs/values.yaml'

    # 2. Ваш Git-репозиторий с файлом values.yaml
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      ref: values

    # 3. Ваш StorageClass из Git
    - repoURL: 'https://github.com/ViktorovPavel/bug-farm-gitops.git'
      targetRevision: HEAD
      path: k8s/systems/openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true