# Отключаем хуки обновления (убираем ошибку ImagePullBackOff)
preUpgradeHook:
  enabled: false

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

localpv-provisioner:
  enabled: true
  # Отключаем встроенное создание StorageClass от Helm (будем управлять через sc.yaml)
  openebsLocalPV:
    enabled: false
  helper:
    baseDir: "/var/local/openebs"
  localpv:
    basePath: "/var/local/openebs"

analytics:
  enabled: false