# Включаем LocalPV Hostpath
localpv-provisioner:
  enabled: true

  # Конфигурация для hostpath
  hostpath:
    enabled: true
    basePath: "/var/local/openebs"

  # Конфигурация для helper
  helper:
    enabled: true
    baseDir: "/var/local/openebs"

# Отключаем все остальные движки
engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
    jiva:
      enabled: false

# Отключаем телеметрию
analytics:
  enabled: false

# Отключаем NDM (Node Disk Manager) если не нужен
ndm:
  enabled: false