# Настройки для Talos OS
nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /var/local-path-provisioner

useNodeNameOnly: true

storageClass:
  name: local-path
  default: true
  reclaimPolicy: Delete

# Ресурсы для слабых нод
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m