# 1. Хранилище для метрик VictoriaMetrics
vmsingle:
  enabled: true
  spec:
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi # Объём под базу метрик

# 2. Хранилище для Grafana
grafana:
  enabled: true
  adminUser: "admin"
  adminPassword: "admin"
  persistence:
    enabled: true
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    size: 200Mi # Наш оптимизированный размер под SQLite