---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB0YKNjid03N2dLPTaQmEC1asKWBpgQWjMXQta+0R0jgizCyUNAPfBnqiVKRNBrQcZyy6quDUaTr2GpAXM/91Jy+KAwoNBCbJo3llF2DHOPSaBYPDqJD2BkZpk42mSe9n6e3bCOogIk3FF9GNokxU6ykZgL2WvzlabyeIdACvSQVW4UIxo6LPfnPoB7AuIBlnd22k6Ex7kk5J5S5lTbYkfLkT6pLsPa7hkX9Cuabt8YwJVKIbslNiA1fbQHinJvOot8SelSXhD2SWGp51A5XubxnDg6JjUDB/YbaPhvnJJ5CYI4EwfzZq6xOTg8TAzfY3Ffi/1gfnwSW50LJgR5ib9RyK2tE3Y/KTXsCrUXPUw8/gY7ReZovtA5+M/03w0JOZ5o9SlNr9f+5VnJZUSAXopEdw0l5XZZ2HloWQhIsSIN1tVV2m8tTqfioh2E6DYkMV2SXp3MR2u/dEKAz5+Fl5RmRX0OWOLbnT2mm7CjNDXRh37ubogvLrW/f9XxsLeRKScuHQFf/hHGxRxXRhIdjpsayngBDLOTpnutCIzVtwfYd22rLafNKVXVhaLF5L62MrzKb6pax8PmSZJDpvFHJiJsdCR27/Rl6PWioJRt4RGi0WC0qix+QzI8p42GiGXZfYsv8wrwNQVhTOak7gknb0Yphv8FIDZrHn9RqJWw6i9sMea8HuN6L3Cy609LgbddUXjMBqW2fI7xVvOuvsveCNrmrJP1VoMHt9y6MF5Uc5qtsOpicKd1aM2/rxsPD8og+WoHeN2PJzdShXoMpC901CZEcornDnHnsSSBUDQ9dyZrP9/PES5+lU3waeQ1rvwg+Y8zch0+tfRnd8fLWFYTTGUDEbiwmZmQKBzlxSmJRhBBvRufka/BYBJbE8OzfeqGemLFJQAj41YAv17kVNKkGL8vBEwqsvUdKGi3M0BIbwOwf5HJ2yVDrjj8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
